sudo: required
dist: trusty
language: cpp

services:
    - docker

compiler:
    - gcc

env:
    - DOCKER_TARGET=xenial

before_install:
    - docker build -t eos:${DOCKER_TARGET} -f .travis/${DOCKER_TARGET} .

script:
    - docker run -it eos:xenial /bin/bash /src/.travis/build-and-test.bash ${DOCKER_TARGET}
